@extends('layouts.admin')
@section('title', 'Getting started')
@section('content')
<div class="topline"><div><span class="page-kicker">Imprint Hub</span><h1>Getting started</h1><p class="muted">Your guide from a new inquiry to completed production.</p></div></div>
<div style="max-width:900px;display:grid;gap:16px">
<section class="card"><h2>1. Start your day</h2><p>Check your Dashboard and Notifications for upcoming work, then open Daily Tasks. Change your password and confirm your email in My Account.</p><a class="button ghost" href="{{ route('admin.tasks.index') }}">Open daily tasks</a></section>
<section class="card"><h2>2. Receive inquiries · Marketing</h2><p>Copy All Client Forms from Share with clients on the dashboard. Clients choose a form and receive a reference number. Review their submission in Inquiries, record contact notes, and update its status. The public update is visible to the client; keep internal notes separate.</p><p>Status or public-update changes saved on the inquiry screen trigger an email attempt when a client email is present. Actual delivery requires configured email service.</p></section>
<section class="card"><h2>3. Plan the event · Marketing</h2><p>Convert the inquiry when ready, or create an event. Check the date, venue, contact details, and scheduling warnings before saving. New events generate a Multimedia coverage request and production tasks automatically.</p></section>
<section class="card"><h2>4. Produce the work · Multimedia</h2><p>Open Event Coverage to see the work booked in. Take on the role you are covering — shooter, photo edit, or video edit — and the rest of the crew take theirs. Automatic routing puts work in the Multimedia queue; check who owns each task before starting. Use Daily Tasks to track progress.</p><p>Check photo and video deadlines, complete the production checklist, upload supporting files, and track revision rounds. Add the final delivery link and record when it has been sent. Clients are notified by email; there is no client media-approval step.</p></section>
<section class="card"><h2>5. Protect your work · Administrator</h2><p>Open System &amp; Security to create, verify, or download a backup and test email delivery. Check failed email attempts after changing provider settings. Store a backup copy away from this computer.</p><p>Keep the launcher running while public forms are needed. Free Cloudflare links can change after restarting; copy the current link from the dashboard before sharing.</p></section>
</div>
@endsection
