@extends('layouts.admin')
@section('title', 'Multimedia Home')
@section('content')
<style>.mm-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.work-row{display:flex;gap:12px;align-items:center;padding:13px 0;border-bottom:1px solid var(--line-soft)}.work-row:last-child{border:0}.work-main{flex:1}.work-main strong{display:block}.count-tile{display:grid;place-items:center;min-width:42px;height:42px;border-radius:12px;background:var(--accent-bg);color:var(--accent-ink);font-weight:800}@media(max-width:900px){.mm-grid{grid-template-columns:1fr}}</style>
<div class="topline"><div><span class="page-kicker">Production desk</span><h1>Multimedia home</h1><div class="muted small">Incoming work, today’s tasks, and upcoming coverage.</div></div><a class="button" href="{{ route('admin.coverage.index') }}">Open coverage board</a></div>
<div class="stats"><div class="card"><strong style="font-size:1.8rem">{{ $queuedTasks->count() }}</strong><div class="muted small">Tasks waiting to be claimed</div></div><div class="card"><strong style="font-size:1.8rem">{{ $requestedCoverage->count() }}</strong><div class="muted small">Coverage requests awaiting response</div></div><div class="card"><strong style="font-size:1.8rem">{{ $myTasks->where('status', 'done')->count() }}/{{ $myTasks->count() }}</strong><div class="muted small">My tasks completed today</div></div></div>
<div class="mm-grid">
    <section class="card"><div class="topline" style="margin-bottom:8px"><h2>From Marketing</h2><a class="edit" href="{{ route('admin.tasks.index') }}">Open queue</a></div>@forelse($queuedTasks as $task)<div class="work-row"><span class="count-tile">T</span><span class="work-main"><strong>{{ $task->title }}</strong><span class="muted small">{{ $task->raisedBy?->name ?? 'Marketing' }}@if($task->event) · {{ $task->event->name }}@endif</span></span><form method="post" action="{{ route('admin.tasks.claim', $task) }}">@csrf<button class="button" type="submit">Take it</button></form></div>@empty<p class="muted small">No tasks are waiting.</p>@endforelse</section>
    <section class="card"><div class="topline" style="margin-bottom:8px"><h2>Coverage requests</h2><a class="edit" href="{{ route('admin.coverage.index', ['show' => 'requested']) }}">View all</a></div>@forelse($requestedCoverage as $coverage)<div class="work-row"><span class="count-tile">C</span><span class="work-main"><strong>{{ $coverage->event->name }}</strong><span class="muted small">{{ $coverage->event->event_date->format('M j') }} · {{ $coverage->event->venue ?: 'Venue not set' }}</span></span><a class="edit" href="{{ route('admin.coverage.edit', $coverage->event) }}">Open</a></div>@empty<p class="muted small">No coverage requests are waiting.</p>@endforelse</section>
    <section class="card"><div class="topline" style="margin-bottom:8px"><h2>My day</h2><a class="edit" href="{{ route('admin.tasks.index') }}">Task board</a></div>@forelse($myTasks as $task)<div class="work-row"><span class="pill pill-{{ $task->status === 'done' ? 'completed' : 'pending' }}">{{ App\Models\Task::STATUSES[$task->status] }}</span><span class="work-main"><strong>{{ $task->title }}</strong>@if($task->event)<span class="muted small">{{ $task->event->name }}</span>@endif</span></div>@empty<p class="muted small">Nothing is assigned to your board today.</p>@endforelse</section>
    <section class="card"><h2>Upcoming shoots</h2>@forelse($upcomingCoverage as $event)<div class="work-row"><span class="count-tile">{{ $event->event_date->format('d') }}</span><span class="work-main"><strong>{{ $event->name }}</strong><span class="muted small">Shooter: {{ $event->coverage->shooter?->name ?? 'Unassigned' }}</span></span><a class="edit" href="{{ route('admin.coverage.edit', $event) }}">Open</a></div>@empty<p class="muted small">No accepted upcoming coverage.</p>@endforelse</section>
</div>
@endsection
